<?php
    $collection = $block->getVideoCollection();
?>
<div>
<div class="cms-content-important">
        <h3>Video Listing</h3>
    </div>
<table class="data table" id="test-data-table">
    <thead>
        <tr>
            <th scope="col" class="col title">Id</th>
            <th scope="col" class="col title">Title</th>
            <th scope="col" class="col author">Description</th>
            <th scope="col" class="col content">Created At</th>
            <th scope="col" class="col actions">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($collection as $key => $data): ?>
            <tr>
                <td data-th="Title" class="col title"><?php echo $data->getVideoId(); ?></td>
                <td data-th="Title" class="col title"><?php echo $data->getTitle(); ?></td>
                <td data-th="Author" class="col author"><?php echo $data->getDescription(); ?></td>
                <td data-th="Date" class="col created_at"><?php echo $data->getCreatedAt(); ?></td>
                <td data-th="Actions" class="col actions">
                    <a href="<?php echo $block->getBaseUrl().'video/'.$data->getUrlKey(); ?>" class="action view">
                        <span>View</span>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>