<form id="feedback-form" data-mage-init='{"validation" : {}}' class="form" action="<?php echo $block->getPostUrl(); ?>" method="post">
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo __('Feedback Form') ?></span></legend>
        <div class="field required">
            <label for="name" class="label"><span><?php echo __('Name') ?></span></label>
            <div class="control">
                <input type="text" id="name"name="name" class="input-text required">
            </div>
        </div>

        <div class="field required">
            <label for="email" class="label"><span><?php echo __('Email') ?></span></label>
            <div class="control">
                <input type="text" id="email"name="email" class="input-text required email">
            </div>
        </div>

        <div class="field required">
            <label for="number" class="label"><span><?php echo __('Feedback') ?></span></label>
            <div class="control">
                <textarea name="content" id="content" class="input-text required"></textarea>
            </div>
        </div>

    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" id="my-button" title="<?php echo __('Submit') ?>"> <span><?php echo __('Submit') ?></span></button>
        </div>
    </div>

</form>