<?php if($block->getData('widgettitle')): ?>
	<h2 class='toptal-title'><?php echo $block->getData('widgettitle'); ?></h2>
<?php endif; ?>
<?php if($block->getData('widgetcontent')): ?>
	<h2 class='toptal-content'><?php echo $block->getData('widgetcontent'); ?></h2>
<?php endif; ?>
<?php if($block->getData('contentnew')): ?>
	<h2 class='toptal-content'><?php echo $block->getData('contentnew'); ?></h2>
<?php endif; ?>